### ISSUE TITLE
Hessian calculation runs into segmentation fault when atoms are frozen

### ISSUE THREAD

**Issue by TamasFoldes** [grimme-lab/xtb#475]
**Describe the bug**
I attempted to calculate the Hessian of a system with several atoms frozen. The calculation terminated with an error showing segmentation fault:
```
writing file \<hessian>.

 projected vibrational frequencies (cm⁻¹)

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x153a79b5fd01 in ???
#1  0x153a79b5eed5 in ???
#2  0x153a797e720f in ???
#3  0x556310f7e468 in ???
#4  0x556310e711a8 in ???
#5  0x556310e6bf98 in ???
#6  0x153a797c80b2 in ???
#7  0x556310e6bffd in ???
#8  0xffffffffffffffff in ???
Segmentation fault (core dumped)
```

**To Reproduce**
Input and output files are attached. 

**Expected behaviour**
Normal termination with the results printed out.

**Additional context**
[output.txt](https://github.com/grimme-lab/xtb/files/6429943/output.txt)
[structure.txt](https://github.com/grimme-lab/xtb/files/6429944/structure.txt)
[xcontrol.txt](https://github.com/grimme-lab/xtb/files/6429945/xcontrol.txt)

**Comment by awvwgk** [comment]
Thanks for reporting, this looks indeed faulty. I'll have to investigate what is throwing up here.

**Comment by jiachenchem** [comment]
A little bit more detail for this issue. xtb 6.4.1 seems to work if number of freezing atoms is smaller than 7. Control and output files are attached. Hope it helps.
[xcontrol_2.txt](https://github.com/grimme-lab/xtb/files/7077946/xcontrol_2.txt)
[output_2.txt](https://github.com/grimme-lab/xtb/files/7077947/output_2.txt)

**Comment by TamasFoldes** [comment]
Thank you for the notification! I tested v 6.4.1 when it came out and noticed the limitation. Is there a plan to further extend the number of frozen atoms possible in a single calculation?

**Comment by lxsep** [comment]
Hello, I am trying to do the same in version 6.6.1 and having the same error as in here. I already tried to extend the memory for the calculation and it is not working.
