### ISSUE TITLE
GFN-FF 2D to 3D converter documentation + segmentation fault

### ISSUE THREAD

**Issue by hoelzerC** [grimme-lab/xtb#603]
**Describe the bug**
The [2D to 3D structure converter](https://xtb-docs.readthedocs.io/en/latest/gfnff.html?highlight=wrtopo#d-to-3d-structure-converter) experiences a `segmentation fault` if bash command not piped to output.

**To Reproduce**
Tested on _xtb version 6.4.1_ with a 2D water molecule in sdf format. However, this should not be specific to the input file (tested with couple of compounds).

`xtb dummy.sdf --gfn 2 --sp` results in 

``` 
           -------------------------------------------------
          |                Calculation Setup                |
           -------------------------------------------------
          program call               : xtb 2d_input.sdf --gfn 2 --sp
          coordinate file            : 2d_input.sdf
forrtl: severe (174): SIGSEGV, segmentation fault occurred
```

whereas `xtb 2d_input.sdf --gfn 2 --sp > dummy_output` terminates correctly. 

**Expected behaviour and suggested solution**
As the documentation [2D to 3D structure converter](https://xtb-docs.readthedocs.io/en/latest/gfnff.html?highlight=wrtopo#d-to-3d-structure-converter) states `xtb 2d_input.sdf --gfn 2 --sp` as example, suggestion include to adapt documentation (maybe also include example input) and catch the segmentation fault.

**Comment by awvwgk** [comment]
Version 6.4.1 (afa7bdf) passes for

```
xtb assets/inputs/sdf/water-openbabel-2D.sdf --gfn 2 --sp --namespace test
```

with fd247e9d38dc418fe38841b66e0ba432c485e5ce

```

 OpenBabel10191919052D

  3  2  0  0  0  0  0  0  0  0999 V2000
    1.7321   -0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
    0.8660    0.5000    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
   -0.0000   -0.0000    0.0000 H   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  2  3  1  0  0  0  0
M  END
$$$$
```

However I see a failure in

```
           ------------------------------------------------- 
          |           Force Field Initialization            |
           ------------------------------------------------- 
 
          distances ...
          ----------------------------------------
          generating topology and atomic info file ...
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source             
libifcore.so.5     00007F8DA05BC0C9  for__signal_handl     Unknown  Unknown
libpthread-2.33.s  00007F8D9F3C0870  Unknown               Unknown  Unknown
xtb                00000000004AEE19  xtb_gfnff_ini2_mp         164  gfnff_ini2.f90
xtb                0000000000B006E1  xtb_gfnff_ini_mp_         230  gfnff_ini.f90
xtb                00000000004D1D56  xtb_gfnff_setup_m          74  gfnff_setup.f90
xtb                00000000004679B7  xtb_gfnff_calcula         125  calculator.f90
xtb                00000000004DDA86  xtb_gfnff_convert          92  struc_converter.f90
xtb                000000000041A7CA  xtb_prog_main_mp_         398  main.F90
xtb                000000000042C71E  MAIN__                     55  primary.f90
xtb                00000000004092A2  Unknown               Unknown  Unknown
libc-2.33.so       00007F8D9F208B25  __libc_start_main     Unknown  Unknown
xtb                00000000004091AE  Unknown               Unknown  Unknown
```

But at a later place.

**Comment by awvwgk** [comment]
Some more insight by gdb, seems like we are getting a bad index from for generating the neighbour map.

```
           ------------------------------------------------- 
          |           Force Field Initialization            |
           ------------------------------------------------- 

          distances ...
          ----------------------------------------
          generating topology and atomic info file ...
          pair mat ...

Thread 1 "xtb" received signal SIGSEGV, Segmentation fault.
0x000055555559b287 in xtb_gfnff_ini2::nbondmat (n=3, nb=..., pair=...) at ../src/gfnff/gfnff_ini2.f90:1511
1511	                 nlist(newi,i)=newatom
(gdb) bt
#0  0x000055555559b287 in xtb_gfnff_ini2::nbondmat (n=3, nb=..., pair=...)
    at ../src/gfnff/gfnff_ini2.f90:1511
#1  0x00005555557b428d in xtb_gfnff_ini::gfnff_ini (env=..., pr=<optimized out>, 
    makeneighbor=<optimized out>, mol=..., gen=..., param=..., topo=..., 
    accuracy=<optimized out>) at ../src/gfnff/gfnff_ini.f90:387
#2  0x00005555555a6ae5 in xtb_gfnff_setup::gfnff_setup (env=..., verbose=.FALSE., 
    restart=.TRUE., mol=..., gen=..., param=..., topo=..., accuracy=0.10000000000000001, 
    version=-1) at ../src/gfnff/gfnff_setup.f90:74
#3  0x00005555555895af in xtb_gfnff_calculator::newgffcalculator (env=..., mol=..., 
    calc=..., fname=..., restart=.TRUE., version=-1, _fname=16)
    at ../src/gfnff/calculator.f90:126
#4  0x00005555555a92f9 in xtb_gfnff_convert::struc_convert (env=..., restart=.TRUE., 
    mol=..., chk=..., egap=0, et=<optimized out>, maxiter=250, maxcycle=0, etot=0, g=..., 
    sigma=...) at ../src/gfnff/struc_converter.f90:92
#5  0x00005555555733de in xtb_prog_main::xtbmain (env=..., argparser=...)
    at ../src/prog/main.F90:399
#6  0x0000555555568040 in xtb_prog_primary () at ../src/prog/primary.f90:55
#7  main (argc=<optimized out>, argv=<optimized out>) at ../src/prog/primary.f90:20
#8  0x00007ffff5eb2b25 in __libc_start_main () from /usr/lib/libc.so.6
#9  0x000055555556809e in _start ()
(gdb) p i
$1 = 1
(gdb) p newi
$2 = 62469
```
